name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        crystal:
          - latest
          - nightly
    runs-on: ${{ matrix.os }}
    container: crystallang/crystal:${{ matrix.crystal }}-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install --ignore-crystal-version --skip-postinstall --skip-executables
    - name: Format
      run: crystal tool format --check
    - name: Run tests
      run: crystal spec -v --error-trace
